### ISSUE TITLE
Missing IrisRestApiClient

### ISSUE THREAD

**Issue by bettse** [nRFCloud/gateway-cordova#2]
There are some externals in the webpack config that aren't included in the repo anywhere, nor documented so far as I can tell:

https://github.com/nRFCloud/gateway-cordova/blob/161cced605dbde976c37055ce56bff2635f455af/webpack.config.js#L80-L83

**Comment by TheBosZ** [comment]
It's this file: https://github.com/nRFCloud/gateway-cordova/blob/master/www/index.bundle.js

I've updated webpack.config.js to have a comment pointing to it.
